name: prorab_plus
description: "Prorab+ - construction management system"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  dio: ^5.7.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  go_router: ^14.2.7

  flutter_svg: ^2.0.10

  intl: ^0.19.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/